file(MAKE_DIRECTORY "${OUTPUT_DIR}")
function(assemble name text export expected)
    set(dir "${OUTPUT_DIR}/${name}")
    file(MAKE_DIRECTORY "${dir}/output with spaces")
    set(output "${dir}/output with spaces/${name}.obj")
    file(REMOVE "${output}")
    file(WRITE "${dir}/input.asm" "${text}")
    execute_process(COMMAND "${KASM}" --format coff --export "${export}" -o "${output}" "${dir}/input.asm"
        WORKING_DIRECTORY "${dir}" RESULT_VARIABLE result ERROR_VARIABLE error)
    if(expected STREQUAL "success")
        if(NOT result EQUAL 0 OR NOT EXISTS "${output}")
            message(FATAL_ERROR "${name}: ${error}")
        endif()
        if(EXISTS "${dir}/input.bin" OR EXISTS "${dir}/input.h")
            message(FATAL_ERROR "COFF invocation also wrote raw output")
        endif()
        file(READ "${output}" object HEX)
        set("${name}_hex" "${object}" PARENT_SCOPE)
    elseif(result EQUAL 0 OR EXISTS "${output}")
        message(FATAL_ERROR "${name}: unsupported object was accepted")
    endif()
endfunction()
assemble(answer "answer: mov eax, 42; ret;" answer success)
set(expected "64860100000000004200000001000000000000002e746578740000000000000000000000060000003c00000000000000000000000000000020005060b82a000000c3616e7377657200000000000001002000020004000000")
if(NOT answer_hex STREQUAL expected)
    message(FATAL_ERROR "Unexpected COFF bytes: ${answer_hex}")
endif()
execute_process(COMMAND "${KASM}" --format coff --export answer "${OUTPUT_DIR}/answer/input.asm"
    RESULT_VARIABLE result OUTPUT_QUIET ERROR_QUIET)
if(result EQUAL 0)
    message(FATAL_ERROR "COFF without an output path was accepted")
endif()
execute_process(COMMAND "${KASM}" --format coff --export answer
    -o "${OUTPUT_DIR}/nonexistent/destination.obj" "${OUTPUT_DIR}/answer/input.asm"
    RESULT_VARIABLE result OUTPUT_QUIET ERROR_QUIET)
if(result EQUAL 0)
    message(FATAL_ERROR "Unwritable output path was accepted")
endif()
assemble(offset "ret; answer: mov eax, 42; ret;" answer success)
string(SUBSTRING "${offset_hex}" 150 8 value)
if(NOT value STREQUAL "01000000")
    message(FATAL_ERROR "Exported label offset was lost")
endif()
assemble(long_name "answer_with_long_name: ret;" answer_with_long_name success)
assemble(missing "other: ret;" answer failure)
assemble(empty "answer:" answer failure)
assemble(data "answer: db 42; ret;" answer failure)
assemble(patches "answer: jmp abs answer;" answer failure)
execute_process(COMMAND "${KASM}" --format coff "${OUTPUT_DIR}/answer/input.asm"
    RESULT_VARIABLE result OUTPUT_QUIET ERROR_QUIET)
if(result EQUAL 0)
    message(FATAL_ERROR "COFF without an export was accepted")
endif()
