file(MAKE_DIRECTORY "${OUTPUT_DIR}")
function(reject name source expected)
    set(case_dir "${OUTPUT_DIR}/${name}")
    file(MAKE_DIRECTORY "${case_dir}")
    file(WRITE "${case_dir}/input.asm" "${source}\n")
    execute_process(COMMAND "${KASM}" --bits 64 "${case_dir}/input.asm"
        WORKING_DIRECTORY "${case_dir}"
        RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error
        TIMEOUT 10)
    if(NOT "${status}" STREQUAL "1")
        message(FATAL_ERROR "${name}: expected exit 1, got ${status}: ${error}")
    endif()
    string(FIND "${error}" "${expected}" position)
    if(position LESS 0)
        message(FATAL_ERROR "${name}: expected '${expected}', got '${error}'")
    endif()
endfunction()
foreach(directive db byte dw word)
    reject(${directive}_empty "${directive};" "expected integer literal")
    reject(${directive}_trailing_comma "${directive} 1,;" "expected integer literal")
    reject(${directive}_missing_comma "${directive} 1 2;" "expected semicolon")
    if(directive STREQUAL "db" OR directive STREQUAL "byte")
        set(limit 256)
        set(range "0..255")
    else()
        set(limit 65536)
        set(range "0..65535")
    endif()
    reject(${directive}_overflow "${directive} ${limit};" "${range}")
    reject(${directive}_negative "${directive} 0-1;" "${range}")
endforeach()
