foreach(required KASM SOURCE OUTPUT_DIR)
    if(NOT DEFINED ${required} OR "${${required}}" STREQUAL "")
        message(FATAL_ERROR "Pass -D${required}=<path> before -P")
    endif()
endforeach()

get_filename_component(KASM "${KASM}" ABSOLUTE)
get_filename_component(SOURCE "${SOURCE}" ABSOLUTE)
get_filename_component(OUTPUT_DIR "${OUTPUT_DIR}" ABSOLUTE)
file(MAKE_DIRECTORY "${OUTPUT_DIR}")
set(output "${OUTPUT_DIR}/exit42")
file(REMOVE "${output}")

execute_process(COMMAND "${KASM}" --format elf --entry _start -o "${output}" "${SOURCE}"
    RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr)
if(NOT result EQUAL 0 OR NOT EXISTS "${output}")
    message(FATAL_ERROR "ELF generation failed (${result}): ${stdout}${stderr}")
endif()

file(SIZE "${output}" size)
if(NOT size EQUAL 4108)
    message(FATAL_ERROR "Expected a 4108-byte ELF file, got ${size}")
endif()
file(READ "${output}" image HEX)
string(TOLOWER "${image}" image)
function(expect_hex byte_offset byte_count expected description)
    math(EXPR start "${byte_offset} * 2")
    math(EXPR length "${byte_count} * 2")
    string(SUBSTRING "${image}" ${start} ${length} actual)
    if(NOT actual STREQUAL expected)
        message(FATAL_ERROR "${description}: expected ${expected}, got ${actual}")
    endif()
endfunction()

expect_hex(0 8 "7f454c4602010100" "ELF identification")
expect_hex(16 2 "0200" "executable type")
expect_hex(18 2 "3e00" "x86-64 machine")
expect_hex(24 8 "0010400000000000" "entry address")
expect_hex(32 8 "4000000000000000" "program-header offset")
expect_hex(52 2 "4000" "ELF header size")
expect_hex(54 2 "3800" "program-header size")
expect_hex(56 2 "0100" "program-header count")
expect_hex(64 4 "01000000" "PT_LOAD type")
expect_hex(68 4 "05000000" "read/execute flags")
expect_hex(80 8 "0000400000000000" "segment virtual address")
expect_hex(96 8 "0c10000000000000" "segment file size")
expect_hex(104 8 "0c10000000000000" "segment memory size")
expect_hex(112 8 "0010000000000000" "segment alignment")
expect_hex(4096 12 "b83c000000bf2a0000000f05" "entry payload")

if(UNIX)
    file(CHMOD "${output}" PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE)
    execute_process(COMMAND "${output}" RESULT_VARIABLE exit_status)
    if(NOT exit_status EQUAL 42)
        message(FATAL_ERROR "ELF exited with ${exit_status}, expected 42")
    endif()
endif()

# The first writer rejects missing entries, data sections, and loader patches.
function(expect_rejected name source_text entry)
    set(source "${OUTPUT_DIR}/${name}.asm")
    set(rejected "${OUTPUT_DIR}/${name}")
    file(WRITE "${source}" "${source_text}\n")
    file(REMOVE "${rejected}")
    execute_process(COMMAND "${KASM}" --format elf --entry "${entry}" -o "${rejected}" "${source}"
        RESULT_VARIABLE rejected_result OUTPUT_QUIET ERROR_QUIET)
    if(rejected_result EQUAL 0 OR EXISTS "${rejected}")
        message(FATAL_ERROR "ELF case ${name} was unexpectedly accepted")
    endif()
endfunction()
expect_rejected(missing_entry "other: ret;" _start)
expect_rejected(empty_entry "_start:" _start)
expect_rejected(data_section "_start: db 42;" _start)
expect_rejected(loader_patch "_start: jmp abs _start;" _start)
