# Reusable CLI test: SOURCE is an existing assembly file; EXPECTED_HEX is optional.
foreach(required KASM SOURCE)
    if(NOT DEFINED ${required} OR "${${required}}" STREQUAL "")
        message(FATAL_ERROR "Pass -D${required}=<path> before -P")
    endif()
endforeach()
get_filename_component(KASM "${KASM}" ABSOLUTE)
get_filename_component(SOURCE "${SOURCE}" ABSOLUTE)
if(NOT EXISTS "${SOURCE}")
    message(FATAL_ERROR "Source file does not exist: ${SOURCE}")
endif()
if(NOT DEFINED OUTPUT_DIR)
    get_filename_component(example_name "${SOURCE}" NAME_WE)
    string(SHA256 source_id "${SOURCE}")
    set(OUTPUT_DIR "${CMAKE_CURRENT_BINARY_DIR}/build/example-tests/${example_name}-${source_id}")
endif()
get_filename_component(OUTPUT_DIR "${OUTPUT_DIR}" ABSOLUTE)
file(MAKE_DIRECTORY "${OUTPUT_DIR}")
# Each invocation writes program.bin in its example's own working directory.
file(REMOVE "${OUTPUT_DIR}/program.bin")
execute_process(COMMAND "${KASM}" "${SOURCE}"
    WORKING_DIRECTORY "${OUTPUT_DIR}"
    RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error
    TIMEOUT 10)
if(NOT "${status}" STREQUAL "0" OR NOT "${error}" STREQUAL "")
    message(FATAL_ERROR "Encoding ${SOURCE} failed: exit ${status}: ${error}")
endif()
if(NOT EXISTS "${OUTPUT_DIR}/program.bin")
    message(FATAL_ERROR "Assembler did not create program.bin")
endif()
file(READ "${OUTPUT_DIR}/program.bin" actual HEX)
string(TOUPPER "${actual}" actual)
string(REPLACE "\r\n" "\n" output "${output}")
string(FIND "${output}" "\n" first_newline)
if(first_newline LESS 0)
    message(FATAL_ERROR "Missing hexadecimal output line: ${output}")
endif()
string(SUBSTRING "${output}" 0 ${first_newline} hex_line)
string(REGEX REPLACE "[ \t]" "" printed "${hex_line}")
if(NOT "${actual}" STREQUAL "${printed}")
    message(FATAL_ERROR "Binary ${actual} differs from stdout: ${output}")
endif()
if(DEFINED EXPECTED_HEX)
    string(REGEX REPLACE "[ \t\r\n]" "" expected "${EXPECTED_HEX}")
    string(TOUPPER "${expected}" expected)
    if(NOT "${actual}" STREQUAL "${expected}")
        message(FATAL_ERROR "Expected ${expected}, got ${actual}")
    endif()
endif()
if(DEFINED EXPECTED_DECODE_FILE)
    file(READ "${EXPECTED_DECODE_FILE}" expected_decode)
    string(REPLACE "\r\n" "\n" expected_decode "${expected_decode}")
    math(EXPR decode_start "${first_newline} + 1")
    string(SUBSTRING "${output}" ${decode_start} -1 decoded)
    if(NOT "${decoded}" STREQUAL "${expected_decode}")
        message(FATAL_ERROR "Decoded listing mismatch.\nExpected:\n${expected_decode}\nGot:\n${decoded}")
    endif()
endif()
message(STATUS "Encoded ${SOURCE}: ${actual}")
message(STATUS "Binary: ${OUTPUT_DIR}/program.bin")
