foreach(case IN ITEMS empty order missing extra limit too_deep)
    execute_process(COMMAND "${DRIVER}" "${case}"
        RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error
        TIMEOUT 10)
    if(NOT "${status}" STREQUAL "0")
        message(FATAL_ERROR "Block case ${case} failed: exit ${status}: ${error}")
    endif()
    set(expected "")
    if(case STREQUAL "missing")
        set(expected "expected closing brace")
    elseif(case STREQUAL "extra")
        set(expected "unexpected closing brace")
    elseif(case STREQUAL "too_deep")
        set(expected "blocks nested too deeply")
    endif()
    if(expected STREQUAL "")
        if(NOT error STREQUAL "")
            message(FATAL_ERROR "Block case ${case} produced a diagnostic: ${error}")
        endif()
    elseif(NOT error MATCHES "${expected}")
        message(FATAL_ERROR "Block case ${case} expected '${expected}', got: ${error}")
    endif()
endforeach()
