foreach(required KASM SOURCE BITS EXPECTED_ERROR)
    if(NOT DEFINED ${required} OR "${${required}}" STREQUAL "")
        message(FATAL_ERROR "Pass -D${required}=<value> before -P")
    endif()
endforeach()
get_filename_component(KASM "${KASM}" ABSOLUTE)
get_filename_component(SOURCE "${SOURCE}" ABSOLUTE)
if(NOT EXISTS "${SOURCE}")
    message(FATAL_ERROR "Source file does not exist: ${SOURCE}")
endif()
if(DEFINED OUTPUT_DIR)
    get_filename_component(OUTPUT_DIR "${OUTPUT_DIR}" ABSOLUTE)
    file(MAKE_DIRECTORY "${OUTPUT_DIR}")
endif()
execute_process(COMMAND "${KASM}" "--bits" "${BITS}" "${SOURCE}"
    WORKING_DIRECTORY "${OUTPUT_DIR}"
    RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error
    TIMEOUT 10)
if("${status}" STREQUAL "0")
    message(FATAL_ERROR "${BITS}-bit mode was unexpectedly accepted")
endif()
string(CONCAT diagnostics "${output}\n${error}")
string(FIND "${diagnostics}" "${EXPECTED_ERROR}" error_position)
if(error_position LESS 0)
    message(FATAL_ERROR "Expected diagnostic '${EXPECTED_ERROR}', got:\n${diagnostics}")
endif()
message(STATUS "Correctly rejected ${BITS}-bit mode")
